### ISSUE TITLE
Clashing with React-Dom 16.0.0

### ISSUE THREAD

**Issue by kenshinman** [arunoda/learnnextjs-demo#14]
Clashing with React-Dom 16.0.0 
```
Error in C:\projects\react\hello-next\node_modules\next\dist\client\next-dev.js
Module not found: Error: Can't resolve 'react-dom/lib/ReactReconciler' in 'C:\projects\react\hello-next\node_modules\next\dist\client'
ModuleNotFoundError: Module not found: Error: Can't resolve 'react-dom/lib/ReactReconciler' in 'C:\projects\react\hello-next\node_modules\next\dist\client'
    at factoryCallback (C:\projects\react\hello-next\node_modules\webpack\lib\Compilation.js:264:39)
    at factory (C:\projects\react\hello-next\node_modules\webpack\lib\NormalModuleFactory.js:247:20)
    at resolver (C:\projects\react\hello-next\node_modules\webpack\lib\NormalModuleFactory.js:65:21)
    at asyncLib.parallel.e (C:\projects\react\hello-next\node_modules\webpack\lib\NormalModuleFactory.js:138:21)
    at C:\projects\react\hello-next\node_modules\async\dist\async.js:3861:9
    at C:\projects\react\hello-next\node_modules\async\dist\async.js:421:16
    at iteratorCallback (C:\projects\react\hello-next\node_modules\async\dist\async.js:996:13)
    at C:\projects\react\hello-next\node_modules\async\dist\async.js:906:16
    at C:\projects\react\hello-next\node_modules\async\dist\async.js:3858:13
    at resolvers.normal.resolve (C:\projects\react\hello-next\node_modules\webpack\lib\NormalModuleFactory.js:130:23)
```

**Comment by arunoda** [comment]
Please use the `next` version `4.0.0-beta.1` for now or use the React 15.
