### ISSUE TITLE
Lazy Loading Components - issue at http://localhost:3000/p/hello-nextjs

### ISSUE THREAD

**Issue by carltonwin8** [arunoda/learnnextjs-demo#18]
Cannot read property 'querySelectorAll' of null
TypeError: Cannot read property 'querySelectorAll' of null
    at Highlight.highlightCode (http://localhost:3000/_next/db69cdf4-c316-42fb-a3b1-e9083ae1575b/webpack/6:9358:33)
    at Highlight.componentDidMount (http://localhost:3000/_next/db69cdf4-c316-42fb-a3b1-e9083ae1575b/webpack/6:9347:18)
    at commitLifeCycles (http://localhost:3000/_next/1513291716391/commons.js:8776:24)
    at commitAllLifeCycles (http://localhost:3000/_next/1513291716391/commons.js:9952:9)
    at HTMLUnknownElement.callCallback (http://localhost:3000/_next/1513291716391/commons.js:548:14)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/_next/1513291716391/commons.js:587:16)
    at invokeGuardedCallback (http://localhost:3000/_next/1513291716391/commons.js:444:27)
    at commitRoot (http://localhost:3000/_next/1513291716391/commons.js:10056:9)
    at performWorkOnRoot (http://localhost:3000/_next/1513291716391/commons.js:11023:42)
    at performWork (http://localhost:3000/_next/1513291716391/commons.js:10973:7)

**Comment by pimmey** [comment]
Seems to be related to [react-highlight](https://github.com/akiran/react-highlight/issues/39) package.

**Comment by SlowburnAZ** [comment]
Same issue here...  has anyone found a solution?

**Comment by Soundvessel** [comment]
Same

```
Cannot read property 'querySelectorAll' of null
TypeError: Cannot read property 'querySelectorAll' of null
    at Highlight.highlightCode (http://localhost:3000/_next/1521243042454/page/p/hello-nextjs.js:14495:33)
    at Highlight.componentDidMount (http://localhost:3000/_next/1521243042454/page/p/hello-nextjs.js:14484:18)
    at commitLifeCycles (http://localhost:3000/_next/1521243042454/commons.js:8776:24)
    at commitAllLifeCycles (http://localhost:3000/_next/1521243042454/commons.js:9952:9)
    at HTMLUnknownElement.callCallback (http://localhost:3000/_next/1521243042454/commons.js:548:14)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/_next/1521243042454/commons.js:587:16)
    at invokeGuardedCallback (http://localhost:3000/_next/1521243042454/commons.js:444:27)
    at commitRoot (http://localhost:3000/_next/1521243042454/commons.js:10056:9)
    at performWorkOnRoot (http://localhost:3000/_next/1521243042454/commons.js:11023:42)
    at performWork (http://localhost:3000/_next/1521243042454/commons.js:10973:7)
```

**Comment by asfourco** [comment]
Was able to resolve this issue by updating the react-highlight package version to `v0.11.1`. See ticket: https://github.com/akiran/react-highlight/issues/39

**Comment by egonyuri** [comment]
@asfourco works well

**Comment by timneutkens** [comment]
https://github.com/arunoda/learnnextjs-demo/pull/35
