### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by gustavlrsn** [arunoda/learnnextjs-demo#3]
On [section 8](https://learnnextjs.com/basics/styling-components/setup), after cloning, checking out the `clean-urls-ssr-markdown` branch, `npm install` and `npm run dev` I get an error. 
```
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object.exports._errnoException (util.js:1034:11)
    at exports._exceptionWithHostPort (util.js:1057:20)
    at Server._listen2 (net.js:1265:14)
    at listen (net.js:1301:10)
    at Server.listen (net.js:1392:7)
    at Function.listen (/Users/gustav/code/learnnextjs-demo/node_modules/express/lib/application.js:618:24)
    at app.prepare.then (/Users/gustav/code/learnnextjs-demo/server.js:22:10)
    at process._tickCallback (internal/process/next_tick.js:109:7)

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hello-next@1.0.0 dev: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hello-next@1.0.0 dev script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hello-next package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hello-next
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hello-next
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/gustav/.npm/_logs/2017-05-01T11_37_52_468Z-debug.log
```

Here's the log file:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'dev' ]
2 info using npm@4.2.0
3 info using node@v7.8.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle hello-next@1.0.0~predev: hello-next@1.0.0
6 silly lifecycle hello-next@1.0.0~predev: no script for predev, continuing
7 info lifecycle hello-next@1.0.0~dev: hello-next@1.0.0
8 verbose lifecycle hello-next@1.0.0~dev: unsafe-perm in lifecycle true
9 verbose lifecycle hello-next@1.0.0~dev: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/gustav/code/learnnextjs-demo/node_modules/.bin:/Users/gustav/.rvm/gems/ruby-2.0.0-p247/bin:/Users/gustav/.rvm/gems/ruby-2.0.0-p247@global/bin:/Users/gustav/.rvm/rubies/ruby-2.0.0-p247/bin:/Users/gustav/.rvm/bin:/bin:/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/ImageMagick/bin:/usr/local/MacGPG2/bin
10 verbose lifecycle hello-next@1.0.0~dev: CWD: /Users/gustav/code/learnnextjs-demo
11 silly lifecycle hello-next@1.0.0~dev: Args: [ '-c', 'node server.js' ]
12 silly lifecycle hello-next@1.0.0~dev: Returned: code: 1  signal: null
13 info lifecycle hello-next@1.0.0~dev: Failed to exec dev script
14 verbose stack Error: hello-next@1.0.0 dev: `node server.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid hello-next@1.0.0
16 verbose cwd /Users/gustav/code/learnnextjs-demo
17 error Darwin 16.4.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
19 error node v7.8.0
20 error npm  v4.2.0
21 error code ELIFECYCLE
22 error errno 1
23 error hello-next@1.0.0 dev: `node server.js`
23 error Exit status 1
24 error Failed at the hello-next@1.0.0 dev script 'node server.js'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the hello-next package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     node server.js
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs hello-next
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls hello-next
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by gustavlrsn** [comment]
Error on my part, I was already running a process on port 3000, closing this :).
