### ISSUE TITLE
Error when visiting a page directly, according to fetch-data-in-client-side section

### ISSUE THREAD

**Issue by soulchainer** [arunoda/learnnextjs-demo#7]
[This section](https://learnnextjs.com/basics/fetching-data-for-pages/fetch-data-in-client-side) states that:

> If you just visit a post page directly (eg:- http://localhost:3000/p/975) you'll be able to see the message printed on the server but not in the client.

But when I try to visit a post page directly, I only get an error, both in server console and in the browser (that pink screen).

In console, I got this:

```sh
Fetched show: Not Found                                                                                                                                                                        
TypeError: Cannot read property 'replace' of undefined                                                                                                                                         
    at Post (/learnnextjs-demo/.next/dist/pages/post.js:48:26)                                                                           
    at /learnnextjs-demo/node_modules/react-dom/lib/ReactCompositeComponent.js:306:16                                                    
    at measureLifeCyclePerf (/learnnextjs-demo/node_modules/react-dom/lib/ReactCompositeComponent.js:75:12)                              
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (/learnnextjs-demo/node_modules/react-dom/lib/ReactCompositeCompone
nt.js:305:14)                                                                                                                                                                                  
    at ReactCompositeComponentWrapper._constructComponent (/learnnextjs-demo/node_modules/react-dom/lib/ReactCompositeComponent.js:280:21
)                                                                                                                                                                                              
    at ReactCompositeComponentWrapper.mountComponent (/learnnextjs-demo/node_modules/react-dom/lib/ReactCompositeComponent.js:188:21)    
    at Object.mountComponent (/learnnextjs-demo/node_modules/react-dom/lib/ReactReconciler.js:46:35)                                     
    at ReactCompositeComponentWrapper.performInitialMount (/learnnextjs-demo/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34
)                                                                                                                                                                                              
    at ReactCompositeComponentWrapper.mountComponent (/learnnextjs-demo/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)    
    at Object.mountComponent (/learnnextjs-demo/node_modules/react-dom/lib/ReactReconciler.js:46:35)
```

And, in the browser:

![next_error](https://user-images.githubusercontent.com/169524/26894072-9fe2a4e6-4bbd-11e7-86ed-f0ad4f0eaeda.png)

**Note**: and, of course, the code it's the same that on examples. The error 500 in browser it's because I did a refresh in that screencapture, but the rest keeps happening when you try to access directly to the page, even when you don't hit f5.

**Comment by arunoda** [comment]
This worked for me well.
Please make sure to follow these steps: https://learnnextjs.com/basics/fetching-data-for-pages/fetching-data-for-pages

And restart your app as mentioned there.

**Comment by sandric** [comment]
Well I got the same. @soulchainer did you found what your error was?

**Comment by soulchainer** [comment]
@sandric Sorry, but if I found it, I don't remember after all this time (it was half a year ago) :(.
Usually I autodocument this kind of thing, but just in that time I didn't, probably because I ended not using nextjs.
Good luck with it.
